
INSERT INTO MulticlassMinimumPayrollThreshold VALUES 
--((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,1,'LableName',1,GETDATE(),1,GETDATE(),NULL)
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,1,'0.55','Automobile Parts and Accessories'							,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,2,'0.65','Gasoline Station'											,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,3,'0.35','Automobile Rentals and Leasing All Other'					,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,4,'0.55','Rubber Tire Dealer'											,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,5,'0.55','Vehicle Sales (No Repair Work)'								,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,6,'0.65','Auto Body Repair'											,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,7,'0.65','Car Wash'													,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,8,'0.65','Auto Conversion or Customization'							,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,9,'0.55','Auto Service or Repair Center'								,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,10,'0.55','Artisan/Handyman'											,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,11,'0.55','Cabinetry or Interior Trim Installation'					,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,12,'0.55','Residential Carpentry'										,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,13,'0.55','Roofing'													,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,14,'0.55','Shop Only - Carpentry'										,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,15,'0.55','Flat Cement Work'											,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,16,'0.55','Concrete Construction'										,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,17,'0.55','Masonry'													,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,18,'0.55','Plastering or Stucco Work'									,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,19,'0.55','HVAC'														,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,20,'0.55','Plumbing and Pipe Fitting'									,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,21,'0.55','Sheet Metal Work'											,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,22,'0.55','Welding or Cutting'											,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,23,'0.55','Drywalling'													,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,24,'0.55','Electrical Work'											,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,25,'0.55','Excavation or Grading'										,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,26,'0.55','Excavation or Grading'										,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,27,'0.55','Insulation Work'											,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,28,'0.4','Lathing'														,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,29,'0.55','Painting'													,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,30,'0.55','Paperhanging or Wallpapering'								,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,31,'0.1','Colleges or Schools - All Other'								,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,32,'0.1','Colleges or Schools - All Other'								,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,33,'0.65','Firefighters'												,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,34,'0.65','Garbage, Ashes or Refuse Collection'						,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,35,'0.65','Police Officers'											,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,36,'0.55','Ambulance Services EMS'										,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,37,'0.65','Dental Office'												,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,38,'0.55','Home Health Aide'											,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,39,'0.65','Medical Laboratories'										,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,40,'0.65','Physician / Doctor''s Office'								,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,41,'0.35','Hospital All Other'											,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,42,'0.65','Veterinary'													,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,43,'0.65','Child or Day Care Center'									,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,44,'0.65','Nursing Home or Assisted Living'							,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,45,'0.35','Retirement Living Centers'									,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,46,'0.65','Amusement Park or Exhibition Operation'						,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,47,'0.55','Museum / Public Library'									,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,48,'0.55','Theaters'													,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,49,'0.65','Camps'														,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,50,'0.55','Hotel/Motel'												,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,51,'0.65','Billiard Hall'												,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,52,'0.65','Bowling Lane'												,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,53,'0.65','Club--Country, Golf, Fishing or Yacht'						,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,54,'0.65','Clubs - Recreation'											,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,55,'0.65','Exercise or Health Club'									,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,56,'0.65','Roller-Skating Rink Operation'								,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,57,'0.65','Shooting Gallery or Range'									,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,58,'0.65','YMCA, YWCA, YMHA or YWHA, Institution'						,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,59,'0.65','Dealers - Hay, Grain or Feed'								,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,60,'0.65','Nurseries'													,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,61,'0.55','Landscape Gardening'										,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,62,'0.65','Lawn Maintenance'											,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,63,'0.65','Parks/Gardens'												,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,64,'0.55','Lawn Sprinkler Installation'								,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,65,'0.55','Tree Pruning, Spraying, Repairing'							,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,66,'0.55','Food Products - Food Sundries - Manufacturing'				,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,67,'0.55','Meat Products - Meat Processing - Manufacturing'			,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,68,'0.55','Cloth, Canvas and Related Products - Manufacturing'			,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,69,'0.55','Cosmetics - Manufacturing'									,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,70,'0.55','Die Casting - Manufacturing'								,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,71,'0.55','Embroidery - Manufacturing'									,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,72,'0.55','Furniture & Cabinets - Manufacturing'						,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,73,'0.55','Instrument - Manufacturing'									,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,74,'0.55','Machinery - Manufacturing'									,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,75,'0.55','Paper - Manufacturing'										,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,76,'0.55','Pharmaceutical or Surgical Goods - Manufacturing'			,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,77,'0.55','Plastics - Manufacturing'									,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,78,'0.55','Plumbing Products - Manufacturing'							,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,79,'0.55','Precision Machined Parts - Manufacturing'					,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,80,'0.55','Bistro - Restaurant'										,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,81,'0.55','Buffet - Restaurant'										,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,82,'0.65','Café or Ice Cream Shop'										,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,83,'0.55','Caterer - Restaurant'										,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,84,'0.55','Family - Restaurant'										,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,85,'0.55','Fast Food - Restaurant'										,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,86,'0.55','Fine-Dining - Restaurant'									,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,87,'0.55','Pizza - Restaurant'											,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,88,'0.65','Bar/Tavern'													,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,89,'0.65','Lounge/Night Club'											,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,90,'0.55','Bakery'														,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,91,'0.65','Coffee Shop'												,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,92,'0.65','Delicatessen'												,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,93,'0.55','Doughnut Shop'												,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,94,'0.65','Grocery'													,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,95,'0.65','Liquore Store'												,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,96,'0.65','Supermarket'												,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,97,'0.65','Bicycle or Bike Shop'										,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,98,'0.65','Book Store'													,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,99,'0.65','Camera and Photographic Supplies Store'						,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,100,'0.65','Clothing Store'											,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,101,'0.65','Convenience Store'											,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,102,'0.65','Department Store'											,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,103,'0.65','Pharmacy / Drug Store'										,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,104,'0.4','Flooring Store'												,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,105,'0.65','Florist Store'												,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,106,'0.65','Furniture Store All Other'									,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,107,'0.65','General Store'												,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,108,'0.65','Jewelry Store'												,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,109,'0.65','Pawn Shop Store'											,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,110,'0.65','Pet and Pet Supply Store'									,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,111,'0.65','Shoe Store'												,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,112,'0.65','Sporting Goods or Gun Store'								,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,113,'0.65','Toy Store'													,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,114,'0.55','Building Material Dealer or Lumber Yard'					,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,115,'0.55','Hardware Store'											,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,116,'0.35','Home Improvement Center - All Other'						,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,117,'0.55','Paint or Wallpaper Store'									,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,118,'0.55','Plumbers or Pipefitting Supplies Store'					,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,119,'0.55','Appliances/Machines - Installation/Repair'					,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,120,'0.55','Burglar and Fire Alarm - Installation/Repair'				,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,121,'0.55','Ceiling/Fixtures - Installation/Repair'					,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,122,'0.55','Fence - Installation/Repair'								,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,123,'0.55','Furniture or Fixtures - Installation/Repair'				,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,124,'0.55','Millwright Work or Machinery - Installation / Repair'		,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,125,'0.35','Swimming Pools or Spa or Hot Tub - Installation / Repair'	,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,126,'0.65','Barber Shop or Hair Salon'									,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,127,'0.65','Beauty Parlor'												,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,128,'0.55','Laundry and Dry Cleaning'									,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,129,'0.65','Nail Salons'												,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,130,'0.65','Sun Tanning Salons'										,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,131,'0.65','Tattoo Parlors'											,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,132,'0.65','Accounting or Tax Services'								,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,133,'0.65','Architects/Engineers'										,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,134,'0.65','Attorneys'													,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,135,'0.65','Auditor'													,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,136,'0.65','Banks/Credit Unions'										,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,137,'0.65','Clerical Office Employees'									,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,138,'0.65','Programming, Development, or Design'						,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,139,'0.65','Recruiting or Employment Agency'							,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,140,'0.65','Insurance Agencies & Brokerages'							,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,141,'0.65','Real Estate Agents & Appraisers'							,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,142,'0.65','Salespersons or Collectors - Traveling'					,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,143,'0.65','Home/Residential Cleaning'									,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,144,'0.55','Property Mgmt - All Other'									,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,145,'0.55','Property Mgmt Condos/Apts - All Other'						,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,146,'0.55','Property Mgmt Mobile Home/Trailer Park - All Other'		,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,147,'0.55','Carpet, Rug, or Upholstery Cleaning'						,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,148,'0.65','Cemetery - Graveyard Operations'							,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,149,'0.65','Exterminator'												,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,150,'0.65','Funeral Director - Funeral Home - Undertaker Services'		,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,151,'0.55','Inspection of Risks'										,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,152,'0.65','Animal Care'												,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,153,'0.55','Locksmith'													,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,154,'0.35','Mailing or Addressing Co. or Letter Service Shop'			,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,155,'0.55','Mobile Crane Rental with Operators'						,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,156,'0.65','Animal Grooming'											,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,157,'0.55','Snow Removal'												,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,158,'0.55','Taxidermist'												,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,159,'0.4','Telecommunications Company - All Other'						,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,160,'0.65','Undertaker'												,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,161,'0.55','Upholstering'												,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,162,'0.55','Bus Company'												,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,163,'0.55','Limousine Company'											,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,164,'0.65','Messenger, Courier, or Delivery Service'					,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,165,'0.55','Taxicab Company'											,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,166,'0.55','Trucking - Local Hauling (less than 200 miles)'			,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,167,'0.55','Trucking - Long Distance Hauling (more than 200 miles)'	,1,GETDATE(),1,GETDATE(),NULL),	
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,168,'0.55','Trucking - Parcel or Package Delivery'						,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,169,'0.55','Storage Warehouse - Cold'									,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,170,'0.55','Storage Warehouse - Furniture'								,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,171,'0.55','Storage Warehouse - General'								,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,172,'0.65','Religious Organizations'									,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,174,'0.65','Commercial Cleaning Services'								,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,175,'0.55','Group Home'												,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,176,'0.55','Assisted Living Facility'									,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,178,'0.55','Window Washing'											,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,179,'0.55','Equipment Rental'											,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,180,'0.55','Towing - Short Haul'										,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,182,'0.55','Towing - Long Haul'										,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),NULL,183,'0.55','Dealers - Hay, Grain or Feed'								,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),5,10,'0.4','Artisan/Handyman'												,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),5,11,'0.4','Cabinetry or Interior Trim Installation'						,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),5,12,'0.4','Residential Carpentry'										,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),5,15,'0.4','Flat Cement Work'												,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),5,17,'0.4','Masonry'														,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),5,18,'0.4','Plastering or Stucco Work'									,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),5,19,'0.4','HVAC'															,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),5,20,'0.4','Plumbing and Pipe Fitting'									,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),5,21,'0.4','Sheet Metal Work'												,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),5,23,'0.4','Drywalling'													,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),5,24,'0.4','Electrical Work'												,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),5,25,'0.4','Excavation or Grading'										,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),5,26,'0.4','Excavation or Grading'										,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),5,29,'0.4','Painting'														,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),5,30,'0.4','Paperhanging or Wallpapering'									,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),5,94,'0.35','Grocery'														,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),5,144,'0.4','Property Mgmt - All Other'									,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),5,145,'0.4','Property Mgmt Condos/Apts - All Other'						,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),5,146,'0.4','Property Mgmt Mobile Home/Trailer Park - All Other'			,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),5,154,'0.65','Mailing or Addressing Co. or Letter Service Shop'			,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),42,106,'0.35','Furniture Store All Other'									,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),7,106,'0.35','Furniture Store All Other'									,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),19,106,'0.35','Furniture Store All Other'									,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR SEQUENCEMulticlassMinimumPayrollThreshold),38,106,'0.35','Furniture Store All Other'									,1,GETDATE(),1,GETDATE(),NULL)
