
--SELECT Id FROM StateMaster Where StateCode='CT'
--$ --> 1,GETDATE(),1,GETDATE(),NULL

INSERT INTO MulticlassMinimumPayrollThreshold(Id,StateId,ClassDescriptionId,MinimumPayrollThreshold,FriendlyName,IsActive,CreatedDate,CreatedBy,ModifiedDate,ModifiedBy)
VALUES 
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),1,CAST('0.55' AS DECIMAL(18,2)),'Automobile Parts and Accessories',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),2,CAST('0.65' AS DECIMAL(18,2)),'Gasoline Station',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),3,CAST('0.35' AS DECIMAL(18,2)),'Automobile Rentals and Leasing All Other',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),4,CAST('0.55' AS DECIMAL(18,2)),'Rubber Tire Dealer',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),5,CAST('0.55' AS DECIMAL(18,2)),'Vehicle Sales (No Repair Work)',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),6,CAST('0.65' AS DECIMAL(18,2)),'Auto Body Repair',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),7,CAST('0.65' AS DECIMAL(18,2)),'Car Wash',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),8,CAST('0.65' AS DECIMAL(18,2)),'Auto Conversion or Customization',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),9,CAST('0.55' AS DECIMAL(18,2)),'Auto Service or Repair Center',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),10,CAST('0.55' AS DECIMAL(18,2)),'Artisan/Handyman',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),11,CAST('0.55' AS DECIMAL(18,2)),'Cabinetry or Interior Trim Installation',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),12,CAST('0.55' AS DECIMAL(18,2)),'Residential Carpentry',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),13,CAST('0.55' AS DECIMAL(18,2)),'Roofing',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),14,CAST('0.55' AS DECIMAL(18,2)),'Shop Only - Carpentry',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),15,CAST('0.55' AS DECIMAL(18,2)),'Flat Cement Work',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),16,CAST('0.55' AS DECIMAL(18,2)),'Concrete Construction',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),17,CAST('0.55' AS DECIMAL(18,2)),'Masonry',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),18,CAST('0.55' AS DECIMAL(18,2)),'Plastering or Stucco Work',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),19,CAST('0.55' AS DECIMAL(18,2)),'HVAC',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),20,CAST('0.55' AS DECIMAL(18,2)),'Plumbing and Pipe Fitting',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),21,CAST('0.55' AS DECIMAL(18,2)),'Sheet Metal Work',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),22,CAST('0.55' AS DECIMAL(18,2)),'Welding or Cutting',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),23,CAST('0.55' AS DECIMAL(18,2)),'Drywalling',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),24,CAST('0.55' AS DECIMAL(18,2)),'Electrical Work',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),25,CAST('0.55' AS DECIMAL(18,2)),'Excavation or Grading',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),26,CAST('0.55' AS DECIMAL(18,2)),'Excavation or Grading',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),27,CAST('0.55' AS DECIMAL(18,2)),'Insulation Work',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),28,CAST('0.4' AS DECIMAL(18,2)),'Lathing',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),29,CAST('0.55' AS DECIMAL(18,2)),'Painting',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),30,CAST('0.55' AS DECIMAL(18,2)),'Paperhanging or Wallpapering',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),31,CAST('0.1' AS DECIMAL(18,2)),'Colleges or Schools - All Other',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),32,CAST('0.1' AS DECIMAL(18,2)),'Colleges or Schools - All Other',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),33,CAST('0.65' AS DECIMAL(18,2)),'Firefighters',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),34,CAST('0.65' AS DECIMAL(18,2)),'Garbage, Ashes or Refuse Collection',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),35,CAST('0.65' AS DECIMAL(18,2)),'Police Officers',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),36,CAST('0.55' AS DECIMAL(18,2)),'Ambulance Services EMS',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),37,CAST('0.65' AS DECIMAL(18,2)),'Dental Office',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),38,CAST('0.55' AS DECIMAL(18,2)),'Home Health Aide',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),39,CAST('0.65' AS DECIMAL(18,2)),'Medical Laboratories',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),40,CAST('0.65' AS DECIMAL(18,2)),'Physician / Doctor''s Office',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),41,CAST('0.35' AS DECIMAL(18,2)),'Hospital All Other',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),42,CAST('0.65' AS DECIMAL(18,2)),'Veterinary',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),43,CAST('0.65' AS DECIMAL(18,2)),'Child or Day Care Center',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),44,CAST('0.65' AS DECIMAL(18,2)),'Nursing Home or Assisted Living',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),45,CAST('0.35' AS DECIMAL(18,2)),'Retirement Living Centers',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),46,CAST('0.65' AS DECIMAL(18,2)),'Amusement Park or Exhibition Operation',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),47,CAST('0.55' AS DECIMAL(18,2)),'Museum / Public Library',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),48,CAST('0.55' AS DECIMAL(18,2)),'Theaters',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),49,CAST('0.65' AS DECIMAL(18,2)),'Camps',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),50,CAST('0.55' AS DECIMAL(18,2)),'Hotel/Motel',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),51,CAST('0.65' AS DECIMAL(18,2)),'Billiard Hall',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),52,CAST('0.65' AS DECIMAL(18,2)),'Bowling Lane',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),53,CAST('0.65' AS DECIMAL(18,2)),'Club--Country, Golf, Fishing or Yacht',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),54,CAST('0.65' AS DECIMAL(18,2)),'Clubs - Recreation',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),55,CAST('0.65' AS DECIMAL(18,2)),'Exercise or Health Club',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),56,CAST('0.65' AS DECIMAL(18,2)),'Roller-Skating Rink Operation',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),57,CAST('0.65' AS DECIMAL(18,2)),'Shooting Gallery or Range',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),58,CAST('0.65' AS DECIMAL(18,2)),'YMCA, YWCA, YMHA or YWHA, Institution',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),59,CAST('0.65' AS DECIMAL(18,2)),'Dealers - Hay, Grain or Feed',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),60,CAST('0.65' AS DECIMAL(18,2)),'Nurseries',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),61,CAST('0.55' AS DECIMAL(18,2)),'Landscape Gardening',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),62,CAST('0.65' AS DECIMAL(18,2)),'Lawn Maintenance',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),63,CAST('0.65' AS DECIMAL(18,2)),'Parks/Gardens',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),64,CAST('0.55' AS DECIMAL(18,2)),'Lawn Sprinkler Installation',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),65,CAST('0.55' AS DECIMAL(18,2)),'Tree Pruning, Spraying, Repairing',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),66,CAST('0.55' AS DECIMAL(18,2)),'Food Products - Food Sundries - Manufacturing',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),67,CAST('0.55' AS DECIMAL(18,2)),'Meat Products - Meat Processing - Manufacturing',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),68,CAST('0.55' AS DECIMAL(18,2)),'Cloth, Canvas and Related Products - Manufacturing',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),69,CAST('0.55' AS DECIMAL(18,2)),'Cosmetics - Manufacturing',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),70,CAST('0.55' AS DECIMAL(18,2)),'Die Casting - Manufacturing',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),71,CAST('0.55' AS DECIMAL(18,2)),'Embroidery - Manufacturing',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),72,CAST('0.55' AS DECIMAL(18,2)),'Furniture & Cabinets - Manufacturing',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),73,CAST('0.55' AS DECIMAL(18,2)),'Instrument - Manufacturing',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),74,CAST('0.55' AS DECIMAL(18,2)),'Machinery - Manufacturing',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),75,CAST('0.55' AS DECIMAL(18,2)),'Paper - Manufacturing',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),76,CAST('0.55' AS DECIMAL(18,2)),'Pharmaceutical or Surgical Goods - Manufacturing',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),77,CAST('0.55' AS DECIMAL(18,2)),'Plastics - Manufacturing',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),78,CAST('0.55' AS DECIMAL(18,2)),'Plumbing Products - Manufacturing',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),79,CAST('0.55' AS DECIMAL(18,2)),'Precision Machined Parts - Manufacturing',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),80,CAST('0.55' AS DECIMAL(18,2)),'Bistro - Restaurant',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),81,CAST('0.55' AS DECIMAL(18,2)),'Buffet - Restaurant',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),82,CAST('0.65' AS DECIMAL(18,2)),'Café or Ice Cream Shop',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),83,CAST('0.55' AS DECIMAL(18,2)),'Caterer - Restaurant',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),84,CAST('0.55' AS DECIMAL(18,2)),'Family - Restaurant',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),85,CAST('0.55' AS DECIMAL(18,2)),'Fast Food - Restaurant',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),86,CAST('0.55' AS DECIMAL(18,2)),'Fine-Dining - Restaurant',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),87,CAST('0.55' AS DECIMAL(18,2)),'Pizza - Restaurant',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),88,CAST('0.65' AS DECIMAL(18,2)),'Bar/Tavern',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),89,CAST('0.65' AS DECIMAL(18,2)),'Lounge/Night Club',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),90,CAST('0.55' AS DECIMAL(18,2)),'Bakery',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),91,CAST('0.65' AS DECIMAL(18,2)),'Coffee Shop',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),92,CAST('0.65' AS DECIMAL(18,2)),'Delicatessen',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),93,CAST('0.55' AS DECIMAL(18,2)),'Doughnut Shop',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),94,CAST('0.65' AS DECIMAL(18,2)),'Grocery',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),95,CAST('0.65' AS DECIMAL(18,2)),'Liquore Store',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),96,CAST('0.65' AS DECIMAL(18,2)),'Supermarket',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),97,CAST('0.65' AS DECIMAL(18,2)),'Bicycle or Bike Shop',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),98,CAST('0.65' AS DECIMAL(18,2)),'Book Store',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),99,CAST('0.65' AS DECIMAL(18,2)),'Camera and Photographic Supplies Store',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),100,CAST('0.65' AS DECIMAL(18,2)),'Clothing Store',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),101,CAST('0.65' AS DECIMAL(18,2)),'Convenience Store',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),102,CAST('0.65' AS DECIMAL(18,2)),'Department Store',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),103,CAST('0.65' AS DECIMAL(18,2)),'Pharmacy / Drug Store',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),104,CAST('0.4' AS DECIMAL(18,2)),'Flooring Store',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),105,CAST('0.65' AS DECIMAL(18,2)),'Florist Store',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),106,CAST('0.65' AS DECIMAL(18,2)),'Furniture Store All Other',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),107,CAST('0.65' AS DECIMAL(18,2)),'General Store',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),108,CAST('0.65' AS DECIMAL(18,2)),'Jewelry Store',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),109,CAST('0.65' AS DECIMAL(18,2)),'Pawn Shop Store',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),110,CAST('0.65' AS DECIMAL(18,2)),'Pet and Pet Supply Store',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),111,CAST('0.65' AS DECIMAL(18,2)),'Shoe Store',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),112,CAST('0.65' AS DECIMAL(18,2)),'Sporting Goods or Gun Store',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),113,CAST('0.65' AS DECIMAL(18,2)),'Toy Store',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),114,CAST('0.55' AS DECIMAL(18,2)),'Building Material Dealer or Lumber Yard',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),115,CAST('0.55' AS DECIMAL(18,2)),'Hardware Store',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),116,CAST('0.35' AS DECIMAL(18,2)),'Home Improvement Center - All Other',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),117,CAST('0.55' AS DECIMAL(18,2)),'Paint or Wallpaper Store',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),118,CAST('0.55' AS DECIMAL(18,2)),'Plumbers or Pipefitting Supplies Store',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),119,CAST('0.55' AS DECIMAL(18,2)),'Appliances/Machines - Installation/Repair',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),120,CAST('0.55' AS DECIMAL(18,2)),'Burglar and Fire Alarm - Installation/Repair',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),121,CAST('0.55' AS DECIMAL(18,2)),'Ceiling/Fixtures - Installation/Repair',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),122,CAST('0.55' AS DECIMAL(18,2)),'Fence - Installation/Repair',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),123,CAST('0.55' AS DECIMAL(18,2)),'Furniture or Fixtures - Installation/Repair',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),124,CAST('0.55' AS DECIMAL(18,2)),'Millwright Work or Machinery - Installation / Repair',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),125,CAST('0.35' AS DECIMAL(18,2)),'Swimming Pools or Spa or Hot Tub - Installation / Repair',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),126,CAST('0.65' AS DECIMAL(18,2)),'Barber Shop or Hair Salon',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),127,CAST('0.65' AS DECIMAL(18,2)),'Beauty Parlor',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),128,CAST('0.55' AS DECIMAL(18,2)),'Laundry and Dry Cleaning',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),129,CAST('0.65' AS DECIMAL(18,2)),'Nail Salons',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),130,CAST('0.65' AS DECIMAL(18,2)),'Sun Tanning Salons',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),131,CAST('0.65' AS DECIMAL(18,2)),'Tattoo Parlors',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),132,CAST('0.65' AS DECIMAL(18,2)),'Accounting or Tax Services',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),133,CAST('0.65' AS DECIMAL(18,2)),'Architects/Engineers',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),134,CAST('0.65' AS DECIMAL(18,2)),'Attorneys',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),135,CAST('0.65' AS DECIMAL(18,2)),'Auditor',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),136,CAST('0.65' AS DECIMAL(18,2)),'Banks/Credit Unions',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),137,CAST('0.65' AS DECIMAL(18,2)),'Clerical Office Employees',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),138,CAST('0.65' AS DECIMAL(18,2)),'Programming, Development, or Design',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),139,CAST('0.65' AS DECIMAL(18,2)),'Recruiting or Employment Agency',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),140,CAST('0.65' AS DECIMAL(18,2)),'Insurance Agencies & Brokerages',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),141,CAST('0.65' AS DECIMAL(18,2)),'Real Estate Agents & Appraisers',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),142,CAST('0.65' AS DECIMAL(18,2)),'Salespersons or Collectors - Traveling',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),143,CAST('0.65' AS DECIMAL(18,2)),'Home/Residential Cleaning',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),144,CAST('0.55' AS DECIMAL(18,2)),'Property Mgmt - All Other',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),145,CAST('0.55' AS DECIMAL(18,2)),'Property Mgmt Condos/Apts - All Other',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),146,CAST('0.55' AS DECIMAL(18,2)),'Property Mgmt Mobile Home/Trailer Park - All Other',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),147,CAST('0.55' AS DECIMAL(18,2)),'Carpet, Rug, or Upholstery Cleaning',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),148,CAST('0.65' AS DECIMAL(18,2)),'Cemetery - Graveyard Operations',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),149,CAST('0.65' AS DECIMAL(18,2)),'Exterminator',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),150,CAST('0.65' AS DECIMAL(18,2)),'Funeral Director - Funeral Home - Undertaker Services',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),151,CAST('0.55' AS DECIMAL(18,2)),'Inspection of Risks',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),152,CAST('0.65' AS DECIMAL(18,2)),'Animal Care',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),153,CAST('0.55' AS DECIMAL(18,2)),'Locksmith',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),154,CAST('0.35' AS DECIMAL(18,2)),'Mailing or Addressing Co. or Letter Service Shop',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),155,CAST('0.55' AS DECIMAL(18,2)),'Mobile Crane Rental with Operators',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),156,CAST('0.65' AS DECIMAL(18,2)),'Animal Grooming',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),157,CAST('0.55' AS DECIMAL(18,2)),'Snow Removal',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),158,CAST('0.55' AS DECIMAL(18,2)),'Taxidermist',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),159,CAST('0.4' AS DECIMAL(18,2)),'Telecommunications Company - All Other',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),160,CAST('0.65' AS DECIMAL(18,2)),'Undertaker',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),161,CAST('0.55' AS DECIMAL(18,2)),'Upholstering',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),162,CAST('0.55' AS DECIMAL(18,2)),'Bus Company',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),163,CAST('0.55' AS DECIMAL(18,2)),'Limousine Company',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),164,CAST('0.65' AS DECIMAL(18,2)),'Messenger, Courier, or Delivery Service',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),165,CAST('0.55' AS DECIMAL(18,2)),'Taxicab Company',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),166,CAST('0.55' AS DECIMAL(18,2)),'Trucking - Local Hauling (less than 200 miles)',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),167,CAST('0.55' AS DECIMAL(18,2)),'Trucking - Long Distance Hauling (more than 200 miles)',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),168,CAST('0.55' AS DECIMAL(18,2)),'Trucking - Parcel or Package Delivery',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),169,CAST('0.55' AS DECIMAL(18,2)),'Storage Warehouse - Cold',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),170,CAST('0.55' AS DECIMAL(18,2)),'Storage Warehouse - Furniture',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),171,CAST('0.55' AS DECIMAL(18,2)),'Storage Warehouse - General',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),172,CAST('0.65' AS DECIMAL(18,2)),'Religious Organizations',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),174,CAST('0.65' AS DECIMAL(18,2)),'Commercial Cleaning Services',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),175,CAST('0.55' AS DECIMAL(18,2)),'Group Home',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),176,CAST('0.55' AS DECIMAL(18,2)),'Assisted Living Facility',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),178,CAST('0.55' AS DECIMAL(18,2)),'Window Washing',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),179,CAST('0.55' AS DECIMAL(18,2)),'Equipment Rental',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),180,CAST('0.55' AS DECIMAL(18,2)),'Towing - Short Haul',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),182,CAST('0.55' AS DECIMAL(18,2)),'Towing - Long Haul',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),183,CAST('0.55' AS DECIMAL(18,2)),'Dealers - Hay, Grain or Feed',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(SELECT Id FROM StateMaster Where StateCode='CA'),10,CAST('0.4' AS DECIMAL(18,2)),'Artisan/Handyman',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(SELECT Id FROM StateMaster Where StateCode='CA'),11,CAST('0.4' AS DECIMAL(18,2)),'Cabinetry or Interior Trim Installation',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(SELECT Id FROM StateMaster Where StateCode='CA'),12,CAST('0.4' AS DECIMAL(18,2)),'Residential Carpentry',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(SELECT Id FROM StateMaster Where StateCode='CA'),15,CAST('0.4' AS DECIMAL(18,2)),'Flat Cement Work',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(SELECT Id FROM StateMaster Where StateCode='CA'),17,CAST('0.4' AS DECIMAL(18,2)),'Masonry',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(SELECT Id FROM StateMaster Where StateCode='CA'),18,CAST('0.4' AS DECIMAL(18,2)),'Plastering or Stucco Work',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(SELECT Id FROM StateMaster Where StateCode='CA'),19,CAST('0.4' AS DECIMAL(18,2)),'HVAC',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(SELECT Id FROM StateMaster Where StateCode='CA'),20,CAST('0.4' AS DECIMAL(18,2)),'Plumbing and Pipe Fitting',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(SELECT Id FROM StateMaster Where StateCode='CA'),21,CAST('0.4' AS DECIMAL(18,2)),'Sheet Metal Work',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(SELECT Id FROM StateMaster Where StateCode='CA'),23,CAST('0.4' AS DECIMAL(18,2)),'Drywalling',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(SELECT Id FROM StateMaster Where StateCode='CA'),24,CAST('0.4' AS DECIMAL(18,2)),'Electrical Work',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(SELECT Id FROM StateMaster Where StateCode='CA'),25,CAST('0.4' AS DECIMAL(18,2)),'Excavation or Grading',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(SELECT Id FROM StateMaster Where StateCode='CA'),26,CAST('0.4' AS DECIMAL(18,2)),'Excavation or Grading',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(SELECT Id FROM StateMaster Where StateCode='CA'),29,CAST('0.4' AS DECIMAL(18,2)),'Painting',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(SELECT Id FROM StateMaster Where StateCode='CA'),30,CAST('0.4' AS DECIMAL(18,2)),'Paperhanging or Wallpapering',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(SELECT Id FROM StateMaster Where StateCode='CA'),94,CAST('0.35' AS DECIMAL(18,2)),'Grocery',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(SELECT Id FROM StateMaster Where StateCode='CA'),144,CAST('0.4' AS DECIMAL(18,2)),'Property Mgmt - All Other',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(SELECT Id FROM StateMaster Where StateCode='CA'),145,CAST('0.4' AS DECIMAL(18,2)),'Property Mgmt Condos/Apts - All Other',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(SELECT Id FROM StateMaster Where StateCode='CA'),146,CAST('0.4' AS DECIMAL(18,2)),'Property Mgmt Mobile Home/Trailer Park - All Other',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(SELECT Id FROM StateMaster Where StateCode='CA'),154,CAST('0.65' AS DECIMAL(18,2)),'Mailing or Addressing Co. or Letter Service Shop',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(SELECT Id FROM StateMaster Where StateCode='TX'),106,CAST('0.35' AS DECIMAL(18,2)),'Furniture Store All Other',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(SELECT Id FROM StateMaster Where StateCode='CT'),106,CAST('0.35' AS DECIMAL(18,2)),'Furniture Store All Other',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(SELECT Id FROM StateMaster Where StateCode='LA'),106,CAST('0.35' AS DECIMAL(18,2)),'Furniture Store All Other',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(SELECT Id FROM StateMaster Where StateCode='RI'),106,CAST('0.35' AS DECIMAL(18,2)),'Furniture Store All Other',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),184,CAST('0.65' AS DECIMAL(18,2)),NULL,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),1185,CAST('0.65' AS DECIMAL(18,2)),NULL,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),1187,CAST('0.65' AS DECIMAL(18,2)),'Clerical|',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),1188,CAST('0.65' AS DECIMAL(18,2)),NULL,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),1189,CAST('0.65' AS DECIMAL(18,2)),NULL,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),1190,CAST('0.65' AS DECIMAL(18,2)),NULL,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),1191,CAST('0.4' AS DECIMAL(18,2)),'Salespersons - Outside|',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),1192,CAST('0.65' AS DECIMAL(18,2)),NULL,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),1193,CAST('0.65' AS DECIMAL(18,2)),NULL,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),1194,CAST('0.65' AS DECIMAL(18,2)),NULL,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),1198,CAST('0.65' AS DECIMAL(18,2)),NULL,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),1199,CAST('0.65' AS DECIMAL(18,2)),NULL,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),1200,CAST('0.65' AS DECIMAL(18,2)),NULL,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),1201,CAST('0.65' AS DECIMAL(18,2)),'Clerical|',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),1202,CAST('0.65' AS DECIMAL(18,2)),NULL,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),1203,CAST('0.65' AS DECIMAL(18,2)),'Clerical|',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),1204,CAST('0.65' AS DECIMAL(18,2)),NULL,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),1205,CAST('0.65' AS DECIMAL(18,2)),NULL,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),1206,CAST('0.65' AS DECIMAL(18,2)),NULL,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),1207,CAST('0.65' AS DECIMAL(18,2)),NULL,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),1209,CAST('0.65' AS DECIMAL(18,2)),'Clerical|',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),1210,CAST('0.65' AS DECIMAL(18,2)),NULL,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),1211,CAST('0.65' AS DECIMAL(18,2)),'Clerical|',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),1212,CAST('0.65' AS DECIMAL(18,2)),'Clerical|',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),1213,CAST('0.65' AS DECIMAL(18,2)),'Clerical|',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),1215,CAST('0.65' AS DECIMAL(18,2)),'Clerical|',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),1216,CAST('0.65' AS DECIMAL(18,2)),NULL,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),1217,CAST('0.65' AS DECIMAL(18,2)),NULL,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),1218,CAST('0.65' AS DECIMAL(18,2)),'Clerical|',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),1219,CAST('0.65' AS DECIMAL(18,2)),'Clerical|',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),1220,CAST('0.65' AS DECIMAL(18,2)),'Clerical|',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),1221,CAST('0.65' AS DECIMAL(18,2)),'Clerical|',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),1222,CAST('0.65' AS DECIMAL(18,2)),NULL,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),1223,CAST('0.65' AS DECIMAL(18,2)),'Clerical|',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),1224,CAST('0.65' AS DECIMAL(18,2)),'Clerical|',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),1225,CAST('0.65' AS DECIMAL(18,2)),'Clerical|',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),1226,CAST('0.65' AS DECIMAL(18,2)),'Clerical|',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),1227,CAST('0.65' AS DECIMAL(18,2)),NULL,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),1228,CAST('0.65' AS DECIMAL(18,2)),'Clerical|',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),1229,CAST('0.65' AS DECIMAL(18,2)),NULL,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),1230,CAST('0.35' AS DECIMAL(18,2)),'Appliance - Installation/Repair',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),1231,CAST('0.65' AS DECIMAL(18,2)),'Clerical|',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),1232,CAST('0.65' AS DECIMAL(18,2)),NULL,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),1233,CAST('0.65' AS DECIMAL(18,2)),'Clerical|',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),1234,CAST('0.65' AS DECIMAL(18,2)),'Clerical|',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),1235,CAST('0.65' AS DECIMAL(18,2)),'Clerical|',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),1236,CAST('0.65' AS DECIMAL(18,2)),'Clerical|',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),1237,CAST('0.65' AS DECIMAL(18,2)),'Clerical|',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),1238,CAST('0.65' AS DECIMAL(18,2)),NULL,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),1239,CAST('0.65' AS DECIMAL(18,2)),'Clerical|',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),1240,CAST('0.65' AS DECIMAL(18,2)),'Clerical|',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),1241,CAST('0.65' AS DECIMAL(18,2)),'Clerical|',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),1242,CAST('0.65' AS DECIMAL(18,2)),'Clerical|',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),1243,CAST('0.65' AS DECIMAL(18,2)),NULL,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),1245,CAST('0.55' AS DECIMAL(18,2)),'Clerical|Salespersons - Outside|',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),1246,CAST('0.55' AS DECIMAL(18,2)),'Clerical|Salespersons - Outside|',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),1247,CAST('0.55' AS DECIMAL(18,2)),'Clerical|Salespersons - Outside|',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),1248,CAST('0.65' AS DECIMAL(18,2)),NULL,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),1249,CAST('0.65' AS DECIMAL(18,2)),'Clerical|',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),1250,CAST('0.55' AS DECIMAL(18,2)),'Clerical|Salespersons - Outside|',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),1251,CAST('0.65' AS DECIMAL(18,2)),'Clerical|',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),1252,CAST('0.55' AS DECIMAL(18,2)),'Clerical|Salespersons - Outside|',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),1253,CAST('0.65' AS DECIMAL(18,2)),'Clerical|',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),1254,CAST('0.65' AS DECIMAL(18,2)),'Clerical|',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),1255,CAST('0.55' AS DECIMAL(18,2)),'Clerical|Salespersons - Outside|',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),1256,CAST('0.55' AS DECIMAL(18,2)),'Clerical|Salespersons - Outside|',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),1257,CAST('0.65' AS DECIMAL(18,2)),'Clerical|',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),1258,CAST('0.55' AS DECIMAL(18,2)),'Clerical|Salespersons - Outside|',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),1259,CAST('0.65' AS DECIMAL(18,2)),'Clerical|',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),1260,CAST('0.65' AS DECIMAL(18,2)),'Clerical|',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),1261,CAST('0.4' AS DECIMAL(18,2)),'Clerical|Retail Store &amp; Sales Staff|Salespersons - Outside|',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),1262,CAST('0.65' AS DECIMAL(18,2)),NULL,1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),1264,CAST('0.65' AS DECIMAL(18,2)),'Clerical|',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),1265,CAST('0.65' AS DECIMAL(18,2)),'Professors, Teachers, and Clerical Employees|',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),1266,CAST('0.55' AS DECIMAL(18,2)),'Carpentry  - Wage At Least $30/hr|Clerical|Salespersons - Outside|',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),1267,CAST('0.2' AS DECIMAL(18,2)),'Art Gallery or Gift Store Employees',1,GETDATE(),1,GETDATE(),NULL),
((NEXT VALUE FOR [SEQUENCEMulticlassMinimumPayrollThreshold]),(NULL),1268,CAST('0.65' AS DECIMAL(18,2)),NULL,1,GETDATE(),1,GETDATE(),NULL)