
DROP INDEX [non_clustered_emailid] ON [OrganisationUserDetail]
GO

ALTER TABLE [dbo].[OrganisationUserDetail] ADD  CONSTRAINT [non_clustered_emailid] UNIQUE NONCLUSTERED 
(
    [EmailID] ASC

)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO  
